### ISSUE TITLE
MASK vs constraint_ports

### ISSUE THREAD

**Issue by mvillius** [leghtas/HFSSdrawpy#35]
Whenever you try to add a mask to a cable with a constraint_port, it leads to the error:

          File "/Users/Vil/Github/drawpylib/drawings/marius/stargatev3_AuRef.py", line 371, in <module>
            chip.draw_cable(reso0_0, constrain0, reso0_1, slope=0.15, name='reso0')

          File "/Users/Vil/Github/HFSSdrawpy/HFSSdrawpy/core/body.py", line 390, in moved
            return func(*new_args, **kwargs)

          File "/Users/Vil/Github/HFSSdrawpy/HFSSdrawpy/core/body.py", line 538, in draw_cable
            port_.widths.append(port_.widths[-1] + 2*self.gap_mask)

        AttributeError: 'NoneType' object has no attribute 'append'

The problem is that the constraint_port is initialized with no "widths","layers","subnames" lists so that nothing can be "append".

A quick way to solve this is to change the following part of the draw_cable method:

        if self.is_mask:
                    for port_ in ports:
                        port_.widths.append(port_.widths[-1] + 2*self.gap_mask)
                        port_.offsets.append(0.0)
                        port_.N += 1
                        if port_.subnames[-1] != 'mask':
                            port_.layers.append(MASK)
                            port_.subnames.append('mask')

into:

        if self.is_mask:
            for port_ in ports:
                if port_.constraint_port:
                    pass
                else:
                    port_.widths.append(port_.widths[-1] + 2*self.gap_mask)
                    port_.offsets.append(0.0)
                    port_.N += 1
                    if port_.subnames[-1] != 'mask':
                        port_.layers.append(MASK)
                        port_.subnames.append('mask')

**Comment by pierreguilmin** [comment]
This should be fixed by #31.
